language: ruby
bundler_args: --without development
env:
  - CI=true

before_script:
  - psql -c 'create database crm_test;' -U postgres
  
rvm:
  - 1.9.2
  
gemfile:
  - Gemfile
  - gemfiles/eventmachine-pre
  
notifications:
  recipients:
    - ti@woese.com
    
branches:
  only:
    - master
    - 0.3.x-stable
    - 0.2.x-stable
    - 0.1.x-stable