language: ruby
bundler_args: --without development

before_install:
  - gem update --system
  - gem --version
  
before_script:
  - bundle install
  - psql -c 'create database crm_test;' -U postgres
  - ./recreate_db
  
#script:
#  - bundle exec rake

env:
  - CI=true
  
rvm:
  - 1.9.2
  
gemfile:
  - Gemfile
  
notifications:
  recipients:
    - ti@woese.com
    
branches:
  only:
    - master
    - 0.3.x-stable
    - 0.2.x-stable
    - 0.1.x-stable